import { Item } from "@/client";
import {
    PiBarbell, PiBeerBottleFill, PiBone, PiBoot, PiBroom, PiCakeFill, PiCarrot,
    PiCassetteTapeBold, PiCoins, PiCookieBold, PiCreditCard, PiCrown, PiDress, PiDribbbleLogo,
    PiEggCrack, PiEyeglassesBold, PiFeather, PiFishSimple, PiFlashlight, PiFlask, PiFloppyDiskBack,
    PiGameController, PiGift, PiGuitar, PiHamburger, PiHammer, PiHeadset, PiKey, PiKnife, PiMaskHappy,
    PiMicrophoneStageBold, PiPants, PiPencil, PiPepper, PiPiggyBank, PiPottedPlant, PiSneaker, PiSunglassesFill,
    PiSword, PiToiletPaper, PiVolleyball, AiOutlineTool, PiBalloon, PiBaseballCap, PiBook
} from "./Icons";
import { FC, SVGProps } from "react";

export type ItemWithIcon = Item & {
    icon: FC<SVGProps<SVGSVGElement>>
}

export const items: ItemWithIcon[] = [
    {
        id: 1,
        name: "Muscle Marbles",
        weight: 5.1,
        price: 52.0,
        icon: PiBarbell,
    },
    {
        id: 2,
        name: "Brewer's Delight",
        weight: 1.12,
        price: 3.2,
        icon: PiBeerBottleFill,
    },
    {
        id: 3,
        name: "Fossil Find",
        weight: 1.52,
        price: 20.3,
        icon: PiBone,
    },
    {
        id: 4,
        name: "Tough Treads",
        weight: 1.23,
        price: 40.1,
        icon: PiBoot,
    },
    {
        id: 5,
        name: "Clean Sweep",
        weight: 0.31,
        price: 10.5,
        icon: PiBroom,
    },
    {
        id: 6,
        name: "Sweet Slice",
        weight: 0.93,
        price: 12.2,
        icon: PiCakeFill,
    },
    {
        id: 7,
        name: "Orange Wonder",
        weight: 0.21,
        price: 2.6,
        icon: PiCarrot,
    },
    {
        id: 8,
        name: "The tool",
        weight: 0.58,
        price: 4.2,
        icon: AiOutlineTool,
    },
    {
        id: 9,
        name: "Flying balloon",
        weight: 0.06,
        price: 0.5,
        icon: PiBalloon,
    },
    {
        id: 10,
        name: "Peak-Pride Cap",
        weight: 0.06,
        price: 0.5,
        icon: PiBaseballCap,
    },
    {
        id: 11,
        name: "Ink Symphony",
        weight: 0.39,
        price: 10.5,
        icon: PiBook,
    },
    {
        id: 50,
        name: "Retro Mixtape",
        weight: 0.32,
        price: 5.9,
        icon: PiCassetteTapeBold,
    },
    {
        id: 51,
        name: "Treasure Trove",
        weight: 0.53,
        price: 30.4,
        icon: PiCoins,
    },
    {
        id: 52,
        name: "Sweet Indulgence",
        weight: 0.24,
        price: 7.5,
        icon: PiCookieBold,
    },
    {
        id: 53,
        name: "Plastic Prosperity",
        weight: 0.02,
        price: 2.2,
        icon: PiCreditCard,
    },
    {
        id: 54,
        name: "Royal Headwear",
        weight: 0.13,
        price: 30.4,
        icon: PiCrown,
    },
    {
        id: 55,
        name: "Elegant Attire",
        weight: 0.55,
        price: 40.6,
        icon: PiDress,
    },
    {
        id: 56,
        name: "Dribbble Delight",
        weight: 0.28,
        price: 15.9,
        icon: PiDribbbleLogo,
    },
    {
        id: 57,
        name: "Dino Surprise",
        weight: 0.56,
        price: 25.2,
        icon: PiEggCrack,
    },
    {
        id: 58,
        name: "Vision Enhancer",
        weight: 0.11,
        price: 15.3,
        icon: PiEyeglassesBold,
    },
    {
        id: 59,
        name: "Airy Plume",
        weight: 0.02,
        price: 3.1,
        icon: PiFeather,
    },
    {
        id: 60,
        name: "Aqua Explorer",
        weight: 1.26,
        price: 12.7,
        icon: PiFishSimple,
    },
    {
        id: 61,
        name: "Illumination Beam",
        weight: 0.52,
        price: 8.6,
        icon: PiFlashlight,
    },
    {
        id: 62,
        name: "Chemist's Companion",
        weight: 0.36,
        price: 12.5,
        icon: PiFlask,
    },
    {
        id: 63,
        name: "Retro Storage",
        weight: 0.21,
        price: 4.8,
        icon: PiFloppyDiskBack,
    },
    {
        id: 64,
        name: "Gamer's Delight",
        weight: 0.63,
        price: 25.1,
        icon: PiGameController,
    },
    {
        id: 65,
        name: "Surprise Package",
        weight: 1.28,
        price: 33.4,
        icon: PiGift,
    },
    {
        id: 66,
        name: "String Serenade",
        weight: 1.53,
        price: 54.6,
        icon: PiGuitar,
    },
    {
        id: 67,
        name: "Burger Bliss",
        weight: 0.82,
        price: 8.4,
        icon: PiHamburger,
    },
    {
        id: 68,
        name: "Mighty Mallet",
        weight: 1.2,
        price: 15.3,
        icon: PiHammer,
    },
    {
        id: 69,
        name: "Waves Headset",
        weight: 0.45,
        price: 20.4,
        icon: PiHeadset,
    },
    {
        id: 70,
        name: "Secret Keeper",
        weight: 0.05,
        price: 7.1,
        icon: PiKey,
    },
    {
        id: 71,
        name: "Sharp Blade",
        weight: 0.32,
        price: 10.2,
        icon: PiKnife,
    },
    {
        id: 72,
        name: "Happy Mask",
        weight: 0.14,
        price: 5.3,
        icon: PiMaskHappy,
    },
    {
        id: 73,
        name: "Stage Star Microphone",
        weight: 0.3,
        price: 25.5,
        icon: PiMicrophoneStageBold,
    },
    {
        id: 74,
        name: "Fashionable Pants",
        weight: 0.7,
        price: 35.6,
        icon: PiPants,
    },
    {
        id: 75,
        name: "Creative Pencil",
        weight: 0.05,
        price: 5.2,
        icon: PiPencil,
    },
    {
        id: 76,
        name: "Spicy Pepper",
        weight: 0.1,
        price: 3.4,
        icon: PiPepper,
    },
    {
        id: 77,
        name: "Piggy Savings",
        weight: 0.5,
        price: 20.7,
        icon: PiPiggyBank,
    },
    {
        id: 78,
        name: "Green Companion",
        weight: 1.22,
        price: 20.2,
        icon: PiPottedPlant,
    },
    {
        id: 79,
        name: "Sneaker Style",
        weight: 0.41,
        price: 26.9,
        icon: PiSneaker,
    },
    {
        id: 80,
        name: "Cool Shades",
        weight: 0.12,
        price: 10.3,
        icon: PiSunglassesFill,
    },
    {
        id: 81,
        name: "Mighty Blade",
        weight: 2.1,
        price: 78.3,
        icon: PiSword,
    },
    {
        id: 82,
        name: "Essential Roll",
        weight: 0.2,
        price: 1.2,
        icon: PiToiletPaper,
    },
    {
        id: 83,
        name: "Beach Sport",
        weight: 0.3,
        price: 12.3,
        icon: PiVolleyball,
    },
];
